<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="style.css">

	<style>
		p.p1{	font-size:25px; color:#FFA032;}
		p.p2{ line-height:20px; font-size:15px; color:#104e8b;}
		p.p3{  line-height:0px; font-size:40px; }
		p.p4{  line-height:0px; font-size:20px;}
		a{text-decoration: none; color:#104e8b;}
		body{background-color: #FCF3CF}	

		.button {height: 150; width:200; background-image: url("images/mug1.jpg");}
	</style>
</head>

<body>

<div class="header">
	
		<table  width="30%" align="left" border="0">
			<td align="center"><p class="p3"><a href="home.php">Designgenics</a></p></td>
		</table>

		<table class="t1" width="50%" align="right" border="0">
			<tr>
				<td><p class="p2" align="center">helpline<br>9969894569/9167014987</p></td>
				<td align="center"><p class="p2"><a href="login.php">Logout</a></p></td>
				<td align="center"><p class="p2"><a href="reg.php">Register</a></p></td>
				<td width="5%"></td>
				
			</tr>
		</table>
</div>
<br><br><br><br><br><br>


<table  align="center" width="80%" align="left" border="0" cellpadding="25">

	<tr>
		<td align="left">1. Acceptance of Terms<br><br>
1.1 This Agreement governs the access and use of all products and services relating to: (i) the Member-created websites (individually, a "Member Site" and collectively, "Member Sites"), and (ii) email hosting services, for which Member subscribes from Designgenics, and (iii) the Facebook Page Builder, and which are provided and administered by Designgenics and or its agents, suppliers, licensors, or third party contractors (collectively, the services are referred to as the "Services"). The general Designgenics Terms of Use, available at www.designgenics.in, are incorporated by reference into and made a part of this Agreement, except to the limited extent that the general Designgenics Terms of Use are expressly modified below. IF MEMBER DOES NOT AGREE TO THE TERMS OF THIS AGREEMENT, MEMBER SHALL NOT PURCHASE, USE OR OTHERWISE ACCESS THE SERVICES OR ANY MEMBER SITES.
1.2 The Services is offered to Member conditioned upon Member's acceptance without modification of this Agreement. Member acknowledges that, from time to time, it may be necessary for Designgenics to update or revise the provisions of the Agreement. By signing up for the Services and accepting this Agreement, Member agrees that Designgenics may change the terms of the Agreement in its sole and absolute discretion without specific notice to Member. If Member does not agree to the changes implemented by Designgenics, Member's sole and exclusive remedy is to cancel Member's subscription to the applicable Services ("Member's Service Account"). Unless explicitly stated otherwise, any new features or products that change, augment or enhance the current Services shall be subject to this Agreement.
1.3 Member's access to and use of the Services is further subject to the Designgenics Privacy Policy which is available on Designgenics's website and is incorporated by reference herein.
<br><br>
2. General Use of the Hosting Service
Member shall not use the Services, in whole or in part, for any purpose that is unlawful or prohibited by this Agreement or any applicable law. Without limiting the generality of the foregoing, Member agrees that Member will not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, frame in another web page, use on any other website or product, transfer, or sell any information, content, artwork, graphics, software, lists of users, databases or other lists, products or services provided through or obtained from the Services other than for use as expressly permitted by this Agreement. This means, among other activities, that Member agrees not to engage in the practices of "screen scraping," "database scraping," or any other activity with the purpose of obtaining lists of users or other information. Member agrees that Member will not use the Services in any manner that could damage, disable, overburden, or impair the Services or interfere with any other person's use and enjoyment of the Services. Member shall not obtain or attempt to obtain any materials or information through any means not intentionally made available or provided for through the Services. Except with the prior written permission of Designgenics, Member agrees that Member will not access or attempt to access password protected, secure or non-public areas of the Services. Without limiting any of Designgenics’s rights or remedies under this Agreement or available to Designgenics at law or in equity, if Member violates any of the terms and conditions herein Member's Service Account may be terminated and Member may be subject to prosecution.
<br><br>
3. Charges and Billing
Designgenics reserves the right to charge fees for the Services or any portion thereof and any applicable fees will be posted on Designgenics’s website. If Member is required to pay a fee for all or any part of the Service for which Member has chosen to subscribe, Member will make an advance payment for all applicable fees incurred by Member in connection with Member's Service Account. Member will be notified by a mail before end of his applicable subscription period that he needs to renew his subscription or else his account would be terminated, unless Member's Service Account is terminated in advance by the end of the then-current subscription period. All fees associated with Member's Service Account shall be paid in the currency referenced on the Designgenics website at checkout. The exchange rate will be determined by Designgenics through a reasonable source. The exchange rate determined by Designgenics shall be undisputable.
Designgenics reserves the right to change any fees (which includes but is not limited to, increasing prices on existing or new Services and charging a fee for upgrades and/or for a service for which Designgenics does not currently charge a fee) at any time and from time to time, provided, however, that Designgenics will provide Member with reasonable notice prior to making any fee changes to existing Services. If Member finds any change to the pricing of any Services to be unacceptable for Member's continued use of the Services, Member is free to cancel such Services and terminate Member's Service Account at any time, Designgenics will refund remaining portion of Member's pre-paid fees on pro rata basis.
Taxes
Member agrees to pay GST or other similar taxes, whether international, national, state or local, however designated, which are levied or imposed or may be levied or imposed, with respect to this Agreement. Member is responsible and liable for any fees, including attorney and collection fees, that Designgenics may incur in its efforts to collect any remaining balances due from Member. This Section shall in no way limit any other remedies available to Designgenics at law or in equity.
Member agrees to mention GST registration number and Entity Name, if applicable.The Member will ensure that the GST registration number and the Entity Name, if applicable corresponds to the billing address provided, as no change in the said details will be allowed once the order is placed.
Member further acknowledges that Designgenics will not be responsible for verification of GST registration number and the Entity name, if applicable. Any tax liability arising consequent to non-compliance of law or due to furnishing of incorrect GST registration number and the Entity name, if applicable shall be borne by the Member. In the event, if Member fails to furnish GST registration number, the Member will be treated as ‘unregistered’ and will not be able to avail any input tax credit.
In any case, the liability of Designgenics under GST regime would be limited to the amount of tax charged by Designgenics.
<br><br>
4. Designgenics Support Services
Designgenics offers certain phone support services at no additional charge. Phone support which is offered at no additional charge is limited to technical questions only. Non-technical questions including, but not limited to, questions relating to design, search engine optimization, marketing planning or similar services, shall not be included in such phone support services.
Members may contact Designgenics Support by dialling 022-6718 6718, Monday - Friday : 10 am - 7 pm Saturday - Sunday from 9 am - 6 pm (Indian Standard Time).
<br><br>
5. Member Registration/Privacy Policy
In order for Member to participate in the Services, Designgenics will require Member to provide specific information about Member and (if applicable) Member's business. Member agrees to provide true, accurate and complete information and to refrain from impersonating or falsely representing Member's affiliation with any person or entity. Member shall maintain with Designgenics a valid and current email address of Member at all times. Member shall be responsible for maintaining the confidentiality of Member’s Service Account and password and shall be responsible for any and all transactions by persons given access to such account or password and any and all consequences of use or misuse of such account and password. Member shall be responsible for all actions by such persons, and shall fully indemnify Designgenics as set forth in Section 17 herein below for such actions.
Any information supplied by Member upon registering for the Services and any other information supplied by Member about Member and/or Member's business (collectively, "Member Data") is subject to Designgenics’s Privacy Policy. Member should review the Designgenics Privacy Policy, a copy of which is available on Designgenics’s website. Designgenics reserves the right to update or change the Privacy Policy from time to time in its sole and absolute discretion. In addition, Member Data may be subject to surveillance and disclosure pursuant to applicable laws, rules and regulations relating to domain name registration, including without limitation rules and regulations imposed by ICANN (as defined below), the TPDNVs (as defined below), and the Registries (as defined below).
<br><br>
6. Member Account Limitations
Member hereby acknowledges that Designgenics may, from time to time, in its sole discretion, establish general practices and limits concerning the use of the Services and Member Site, including without limitation, (a) the maximum number of days that specific Services offerings, such as email messages, guest book entries, discussion board postings or other content posted on the Member's Site (to the extent available and subscribed for) will be retained by Designgenics, (b) maximum limits on bandwidth usage that will be allotted to Member, (c) maximum limits on storage space, (d) the maximum number of Member Sites and/or email addresses/accounts per Member's Service Account, (e) the maximum number of photographs or other data (if any) according to the type of Member's Service Account, (f) maximum limits on the number of pages within each Member Site, and (g) maximum time limitations for the retention of Member Content (as defined below) following any trial periods or account cancellation. Designgenics further reserves the right to delete at any time, in its sole discretion and without prior notice, duplicate images uploaded for printing. Any of the foregoing limits will be consistent with the Services (including any upgrades) for which Member has registered. Member agrees that Designgenics has no responsibility or liability for the deletion or failure to store any content maintained or transmitted by the Services, including without limitation any Member Content. Member further acknowledges and agrees that Designgenics reserves the right to change these general practices and limits at any time, in its sole discretion. If Member finds any such changes to be unacceptable for Member's continued use of the Services, Member is free to cancel the Services and terminate Member's Service Account at any time. Designgenics will refund remaining portion of Member's pre-paid fees on pro rata basis.
<br><br>
7. Exchange of Information; Monitoring
The Service enables Members to disseminate and exchange thoughts and opinions to and with other users or the public. Designgenics is under no obligation, but does reserve the right in its sole discretion, to monitor, correct, pre-screen, filter, modify, intercept and analyze traffic of, copy, backup, redirect, transmit, refuse, limit access to, suspend, freeze, and remove any and all such thoughts, opinions, and other Member Content, Member Data, End-User Data etc. posted through the Services or stored in its servers without notice at any time. Designgenics is not responsible for the appropriateness, legality, integrity, accuracy, sufficiency, correctness, veracity, completeness, or timeliness of any such Member Content. Designgenics also reserves the right to disclose any information or materials belonging to any person or entity as necessary to satisfy any applicable law, rule, regulation, legal process, governmental request or contractual obligation binding upon Member. Member acknowledges that Member should always use caution when posting any personally identifying information about Member or Member's employees on the Services, the Member Site, or any other user sites. Designgenics reserves the right to prohibit the use of any of its services in connection with any specially designated nationals (SDNs) as listed by the governmental authorities or having Country-Code Top Level Domain Name/ccTLD of any country designated by authorities such as Office of Foreign Assets Control (OFAC) or such other authority as having limited or comprehensive trade sanctions imposed by the government of India and or countries in which Designgenics has operations or presence for reasons of anti-terrorism, non-proliferation, narcotics trafficking, or other reasons.
<br><br>
8. Member Conduct
Member's right to use the Services is personal to Member and or Member's company and its employees (if applicable). Member, and not Designgenics, is entirely responsible for all Member Content. The term ‘Member Content’ shall include without limitation all information, data, text, literature, software, music, sound, photographs, graphics, designs, video, messages or all other materials and content, as applicable, posted or linked to by Member or its affiliates, agents, employees, representatives or customers via the Services, including, without limitation, any such information, data, text, literature, software, music, sound, photographs, graphics, designs, video, messages or all other materials and content posted or linked to on any Member Site (including, without limitation, as part of a domain name selected or used by Member) (collectively, “Member Content”). Member, and not Designgenics, is responsible for compliance with all laws, regulations and ordinances connected with all aspects of the creation, use and maintenance of the Member Content, Services and Member Sites by Member and its affiliates, employees, agents, representatives and customers. Without limiting the generality of the foregoing, Member, and not Designgenics, is responsible for compliance with all policies, rules, procedures, regulations, and other terms and requirements of the Internet Corporation for Assigned Names and Numbers (“ICANN”), the applicable registry governing the registration of the domain name associated with the Member Site (each, a “Registry”), and any applicable independent Third Party Domain Name Vendors (collectively, “TPDNVs”) responsible for the registration of the domain name associated with the Member Site. Member shall not use the Member Content, Services or Member Sites for any illegal purpose in violation of any local, state, federal or foreign law. Member must provide all required and appropriate warnings, information and disclosures, comply with all applicable laws and regulations, and take all other required and appropriate actions in connection with the creation, use and maintenance of the Member Content, Services and Member Sites by Member and its affiliates, employees, agents, representatives and customers. If the Services or Member Sites do not provide adequate facility or features for Member to provide such information or take such actions, then Member shall not create, use or access the Member Content, Services or Member Sites or permit any other party to do so.
With respect to any Member Content, Member Data, or End-User Data (as defined below) on the Services and Member Sites, Member agrees not to submit, post, upload, transmit or otherwise make available any Member Content, Member Data, End-User Data or other information:
a. that is misleading to others, including but not limited to consumers or other visitors to Member Sites;
b. that is unlawful, threatening, abusive, harassing, tortious, defamatory, obscene, harmful, libelouslibellous, invasive of another's privacy, hateful, or racially or ethnically objectionable;
c. in respect of which Member does not have a right to submit, post, upload, transmit or otherwise make available under any law (including without limitation data privacy laws or export control restrictions) or under contractual or fiduciary relationships (such as information learned or disclosed as part of employment relationships or under nondisclosure agreements);
d. that infringes or violates any person's patent, trademark, trade secret, copyright, proprietary right or other intellectual property rights;
e. that contains viruses or any other computer codes, worms, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment and/or that attempts to access the accounts of others, or attempts to penetrate security measures of Designgenics, its vendors or suppliers or other entities' systems ("hacking"), whether or not the intrusion results in corruption or loss of data or harms any person;
f. that imposes an unreasonable or disproportionately large load on Designgenics's infrastructure or that exceeds the limits provided by Designgenics in respect of the Services for which Member registered; or
g. that includes any unsolicited or unauthorized advertising, promotional materials, "spam," "chain letters," "junk mail", “mail-bombing,” “e-mail harvesting,” or any other similar form of solicitation.
h. that includes phishing (identity theft), pharming, distribution of virus or malware, child pornography, fast flux techniques, running botnet command and control, network attacks, money laundering schemes (Ponzi, Pyramid, Money Mule, etc.).
i. that has pirated software or warez.
h. that is in Designgenics’s sole discretion illegal, unlawful, or otherwise inappropriate.
h. relates to prostitution, escort services, or sex trafficking, all whether legal or not.
With respect to use of the Services and Member Sites, Member further agrees not to:
a. interfere with, disrupt or harm in any way the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies or regulations of network operators connected to the Services;
b. intentionally or unintentionally violate any applicable local, state, national or foreign laws, including, but not limited to, rules and regulations promulgated by governmental authorities such as the Ministry of Information Technology, the Reserve Bank of India, the Securities and Exchange Board of India and the Ministry of Corporate Affairs , any rules and regulations of national or other securities exchanges, including without limitation, Information Technology (Intermediaries Guidelines) Rules, 2011 and the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 and any other applicable regulations having the force of law;
c. impersonate any person or entity or falsely state or otherwise misrepresent Member’s affiliation with any person or entity; intentionally omit, delete, forge or misrepresent transmission information, including any headers, return mailing, and internet protocol (IP) addresses; or otherwise manipulate any identifiers in order to disguise the origin of any Member Content transmitted through the Services;
d. promote or provide instructional information about illegal activities, promote physical harm or injury against any group or individual, or promote any act of cruelty to animals;
e. sell, distribute, disseminate or link to any sites for marketing, sales, or distribution of: firearms, explosives, ammunition, tobacco products and any other products or services that (i) Member cannot legally sell, (ii) are misrepresented, and/or (iii) if sold via a Member Site, could cause Designgenics to violate any law, statute or regulation;
f. post or disclose any personal or private information or images about children or any third party without their express written consent (or a parent's express written consent in the case of a minor), or engage in any activities that would violate the personal privacy rights of others;
g. intentionally or unintentionally violate any policies, rules, procedures, regulations, or other terms or requirements of ICANN, the Registry, or the applicable TPDNV responsible for the registration of the domain name associated with the Member Site;
h. violate any third party contracts to which Member is subject as a result of its access to or use of the Services; or
i. encourage, permit or enable any of its representatives, agents, employees, affiliates, customers or any other third party to do any of the foregoing.
Designgenics may immediately terminate Member's Service Account and Member’s and its representatives’, agents’, employees’, affiliates’, customers’ or any other third party’s access to and use of all or part of the Services in the event Designgenics reasonably concludes that Member and its representatives, agents, employees, affiliates, customers or any other third party is or may be in breach of any of the above listed rules of conduct.
<br><br>
9. Third Party Content
Member agrees that hot keys, hyperlinks, logos, marks, information may be created/inserted/put on Member Site by Designgenics. No compensation of whatsoever nature shall be payable by Designgenics to Member.
For Member's convenience, the Services may contain products, services, content and information from third party providers (such as advertisers and affiliates) and/or links to their websites ("Third Party Content"). Such Third Party Content is not under the control of Designgenics and Designgenics is not responsible for such content, including, without limitation, any link contained in such Third Party Content, or any changes or updates to such Third Party Content. Designgenics is under no obligation, but does reserve the right in its sole discretion to pre-screen Third Party Content available on the Services. Designgenics is not responsible for, and hereby disclaims all liability for and makes no representations or warranties for any Third Party Content. Such inclusion of Third Party Content is only as a convenience, and the inclusion of such Third Party Content does not imply endorsement by Designgenics of such Third Party Content or the affiliate or advertiser. Member may be subjected to additional and/or different terms, conditions, and privacy policies when using third party products, services, content, software, or sites and agrees to comply with any and all end-user obligations or terms and conditions imposed by the providers of such Third Party Content. Designgenics reserves the right to remove any Third Party Content that does not meet Designgenics’s standards/policies/procedures/guidelines, but Designgenics is not responsible for any failure or delay in removing such Third Party Content.
Designgenics is not and will not be responsible for (i) the terms and conditions of any transaction between Member and any third party, (ii) any insufficiency of, suspension of or problems with any such third party's service, background, insurance, credit or licensing, or (iii) the quality of any Third Party Content provided by any third party or any other legal liability arising out of or related to any Third Party Content. In the event that Member has a dispute with any such third party, Member releases Designgenics (and its affiliates, suppliers, agents and employees) from any and all claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes.
Member agrees to expressly authorize Designgenics to send service related transactional SMS messages, even in the case that Member's contact number is listed as DND with the concerned telecom regulatory authority.
<br><br>
10. DISCLAIMER OF WARRANTIES
NOTWITHSTANDING ANYTHING CONTAINED HEREIN, MEMBER EXPRESSLY UNDERSTANDS AND AGREES THAT: (A) MEMBER'S USE OF THE SERVICES, INCLUDING, WITHOUT LIMITATION, THE CREATION, USE AND MAINTENANCE OF THE MEMBER SITE, IS AT MEMBER'S SOLE RISK. Designgenics AND ITS SUPPLIERS PROVIDE THE SERVICES, INCLUDING WITHOUT LIMITATION ALL CONTENT, SOFTWARE, FUNCTIONS, MATERIALS AND INFORMATION MADE AVAILABLE ON OR ACCESSED THROUGH THE SERVICES AND THE MEMBER SITES "AS IS", “WHERE IS” AND “AS AVAILABLE” BASIS, AND WITHOUT ANY WARRANTY, REPRESENTATION OR CONDITION OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT; (B) Designgenics AND ITS SUPPLIERS MAKE NO WARRANTY OR COVENANT OR REPRESENTATION AND HEREBY EXPRESSLY DISCLAIMS ALL WARRANTIES AND COVENANTS AND REPRESENTATIONS (I) THAT THE SERVICES OR MEMBER SITES WILL MEET MEMBER'S REQUIREMENTS, (II) THAT THE SERVICES OR MEMBER SITES WILL BE UNINTERRUPTED, TIMELY, WITHOUT DOWN-TIME, SECURE OR ERROR-FREE OR THAT DEFECTS WILL BE CORRECTED, (III) REGARDING THE RELIABILITY, ACCURACY, COMPLETENESS, VALIDITY OR TRUTHFULNESS OF ANY INFORMATION, MATERIAL OR OTHER CONTENT OBTAINED THROUGH USE OF THE SERVICES OR MEMBER SITES; (IV) THAT ANY INFORMATION, DATA, DOWNLOAD AVAILABLE ON OR THROUGH HOSTING SERVERS WILL BE FREE OF INFECTION BY VIRUSES, WORMS, TROJAN HORSES, BUGS, CODES, OR ANYTHING ELSE MANIFESTING DESTRUCTIVE PROPERTIES, OR (V) THAT THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED OR OBTAINED BY MEMBER THROUGH THE SERVICES WILL MEET MEMBER'S EXPECTATIONS; AND (C) ANY INFORMATION, MATERIAL OR OTHER CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES OR MEMBER SITES, IS DONE AT MEMBER'S OWN DISCRETION AND RISK, AND MEMBER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO MEMBER'S OR THIRD PARTIES’ COMPUTER SYSTEMS OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH INFORMATION, MATERIAL OR OTHER CONTENT. FURTHERMORE, Designgenics NEITHER WARRANTS NOR MAKES ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF SERVICES AND ANY OTHER SOFTWARE / API / SPECIFICATION / DOCUMENTATION / APPLICATION SERVICES IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE.
<br><br>
11. LIMITATION OF LIABILITY
NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS AGREEMENT OR OTHERWISE, IN NO EVENT SHALL Designgenics AND/OR ITS AFFILIATES, EMPLOYEES, AGENTS, REPRESENTATIVES, LICENSORS, CUSTOMERS OR SUPPLIERS BE LIABLE FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL OR CONSEQUENTIAL, OR ANY OTHER DAMAGES OF ANY KIND, ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF USE, DATA, OR PROFITS (HOWEVER ARISING, INCLUDING NEGLIGENCE) EVEN IF Designgenics OR ANY OF SUCH PARTIES HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. IN ADDITION, WITHOUT LIMITING THE GENERALITY OF THE FOREGOING OR ANY OTHER PROVISION IN THIS AGREEMENT, IN NO EVENT SHALL Designgenics AND/OR ITS AFFILIATES, EMPLOYEES, AGENTS, REPRESENTATIVES, LICENSORS, CUSTOMERS OR SUPPLIERS BE LIABLE IN ANY RESPECT ARISING OUT OF OR IN CONNECTION WITH: (A) THE USE OR INABILITY TO USE OF THE SERVICES OR MEMBER SITES, (B) THE PROVISION OF OR FAILURE TO PROVIDE SERVICES OR MEMBER SITES, (C) ANY MEMBER CONTENT OR OTHER INFORMATION, SOFTWARE, PRODUCTS, SERVICES OR RELATED GRAPHICS OBTAINED OR PROVIDED THROUGH THE SERVICES OR MEMBER SITES OR OTHERWISE ARISING OUT OF THE CREATION, USE OR MAINTENANCE OF THE SERVICES OR MEMBER SITES, (D) STATEMENTS OR CONDUCT OF MEMBER OR ANY THIRD PARTY ON OR WITH RESPECT TO THE SERVICES OR MEMBER SITES, OR (E) ANY DOMAIN NAME DISPUTES ARISING FROM OR RELATING TO A DOMAIN NAME SELECTED BY MEMBER FOR USE WITH THE MEMBER SITE.
<br><br>
12. Additional Representations and Warranties and additional Covenants
Member represents, warrants, and covenants that (a) Member has the power and authority to enter into this Agreement; (b) Member, if being a natural person, is at least eighteen (18) years of age; and, (c) Member will only access and use the Services and Member Sites in accordance with this Agreement. Member further agrees that it is and will at all times be, in full compliance with all applicable laws, regulations, rules and ordinances regarding its business, the creation, use and maintenance of the Services, Member Sites, Member Content, Member Data, End-User Data and other data, including without limitation applicable data protection laws and export control laws, and otherwise as related to this Agreement and Member’s performance hereunder.(d) Member shall obtain the necessary registration under the GST and furnish the returns on time without causing inconvenience to Designgenics.
<br><br>
13. Proprietary Rights to Member Content
Designgenics does not claim ownership of the Member Content that Member provides to Designgenics or through the Services and/or that Member places on the Member Site, and Designgenics acknowledges and agrees that, subject to the terms and conditions of this Agreement, Member will retain any and all applicable copyright and other intellectual property rights in any Member Content it has. Notwithstanding the foregoing, Member hereby grants Designgenics a non-exclusive, worldwide, irrevocable, perpetual, unlimited, assignable, sub-licensable, royalty-free, license to (i) copy, host, use, reproduce, modify, prepare derivative works of, improve, distribute, transmit, publish, remove, retain, add to, combine with information provided by third parties, and publicly display the Member Content (a) on and through the Services and Member Sites for the purpose of creating, operating and maintaining the Services and Member Sites and (b) in Designgenics’s promotional and advertising materials for the limited purpose of promoting the Services, and (ii) sublicense to third parties such Member Content to the extent necessary for the creation, operation, and maintenance of, in part or in whole, the Services and Member Sites. Member also hereby grants Designgenics the perpetual and irrevocable right to delete any or all of the Member Content from Designgenics’s servers, the Services and the Member Site, whether intentionally or unintentionally, and for any reason or no reason, without any liability of any kind to Member or any other person. Member agrees that even though Member retains certain copyright or other intellectual property rights in the Member Content, Member does not own the Member’s Service Account used to access the Services or Member Site, nor does Member own any data stored on Designgenics servers (including without limitation any data representing or embodying any or all of the Member Content). No compensation will be paid to Member with respect to Designgenics’s or its sublicensee's use of the materials as licensed in accordance with the foregoing terms. By submitting, posting, uploading, transmitting or otherwise making available any Member Content or by posting messages, uploading files, inputting data, submitting any feedback or suggestions, or engaging in any other form of communication with or through the Services or any Member Site, Member warrants and represents that Member owns or otherwise controls the rights necessary to do so and to grant Designgenics the license set forth above, and, pursuant to the terms set forth in Section 17, Member will defend, indemnify and hold harmless Designgenics and the other Indemnified Parties from any third party claim related to a breach of any of the foregoing representations and warranties.
<br><br>
14. Designgenics Proprietary Rights/Software Licenses
Member hereby agrees and acknowledges that the Services and Member Sites and any software used in connection with the Services and Member Sites (the "Software") contain proprietary and confidential information of Designgenics and/or its licensors that is protected by applicable copyright, trade secrets, trademarks, and other intellectual property and other laws. No reproduction, distribution, or transmission of the proprietary materials of the Services or the Software is permitted without the express written consent of Designgenics. Member further agrees and acknowledges that content contained in sponsor advertisements or information presented to Member through the Services and advertisers is protected by applicable copyrights, trademarks, service marks, patents and other proprietary rights and laws. Any rights not expressly granted herein are reserved to Designgenics.
On the condition that Member complies with all of its obligations under this Agreement, Designgenics grants Member a non-exclusive, revocable, non-transferable, non-sub-licensable, limited license to use the Software for the purposes of utilizing the Services and operating and maintaining the Member Sites, in each case, solely to the extent provided for herein. Member may not sub-license or charge others to use or access the Software. The Software is owned by Designgenics and/or its licensors and is protected to the maximum extent permitted by copyright laws and international treaty provisions. Any reproduction, modification, creation of derivative works from, reverse engineering, redistribution or retransmission of the Software is expressly prohibited, and may result in severe civil and criminal penalties. The Software, its structure, sequence and organization and source code are considered trade secrets of Designgenics and its licensors and are protected by trade secret laws.
WITHOUT LIMITING THE FOREGOING, COPYING OR REPRODUCING THE SOFTWARE TO ANY OTHER SERVER OR LOCATION FOR FURTHER REPRODUCTION OR REDISTRIBUTION IS EXPRESSLY PROHIBITED. MEMBER SHALL NOT DECOMPILE OR DISASSEMBLE, REVERSE ENGINEER OR OTHERWISE ATTEMPT TO DISCOVER ANY CODE INCLUDING (SOURCE CODE) CONTAINED IN ANY SOFTWARE PROVIDED HEREUNDER EXCEPT AS AND SOLELY TO THE EXTENT PERMITTED UNDER APPLICABLE LAW NOTWITHSTANDING THIS PROVISION.
CONFIDENTIAL INFORMATION
Member recognises that it may be given and have access to Confidential Information of Designgenics. Member undertakes not to use any such Confidential Information, for its own purposes except as permitted hereunder, without the prior written consent of Designgenics. Member further undertakes that it shall at all times during and after termination of this Agreement keep the Confidential Information confidential and not disclose to any third party. The contents of this Agreement shall also be kept confidential. The term “Confidential Information” means any and all information disclosed to or otherwise acquired by Member including its affiliates, directors, officers, representative and or employees from Designgenics or its affiliates, associates, representatives, agents or employees, whether communicated in writing, orally, electronically, photographically, or in recorded or any other form, including, but not limited to operating information and strategies, data, media, client list, target clients, know-how, designs, drawings, specifications, source codes, technical information, concepts, reports, methods, processes, techniques, operations, devices, and the like, whether or not the foregoing information is patented, tested, reduced to practice, or subject to copyright.
No announcement, circular, press releases, advertising, marketing materials or promotional materials in connection with the subject matter of this Agreement shall be made or issued (whether in print, electronically or otherwise) by or on behalf of Member without the prior written consent of Designgenics.
Upon request of Designgenics, Member undertakes to immediately return to Designgenics or (at Designgenics’s instructions) destroy or have destroyed all Confidential Information disclosed to it under this Agreement in any form whether physical or in machine readable.
Member shall during and even after termination of this Agreement hold and keep in strictest confidence any and all Confidential Information and shall treat the Confidential Information with at least the same degree of care and protection as it would treat its own Confidential Information. Member also agrees to use the greatest degree of care to avoid unauthorized dissemination, access, disclosure or publication of the Confidential Information. Member shall promptly provide Designgenics with notice of any actual or threatened breach of this Section. Member does not acquire any Intellectual Property Rights under this Agreement or through any disclosure hereunder, except the limited right to use such Confidential Information in accordance with the terms of this Agreement.
The disclosure to any of the employees of Member shall be on a need-to-know basis and only to the extent necessary for each of them to perform its duties in relation to its obligations under this Agreement, provided, Member binds such recipient to terms at least as restrictive as those stated in this Agreement. Member shall fully co-operate with Designgenics to enforce the confidentiality covenants against such recipients.
The provisions of this Section shall survive the termination of this Agreement.
<br><br>
15. Designgenics Proprietary Rights in Provided Designs, Artwork and other Content
As part of the Hosting Service, Designgenics may provide Member access to and use of graphics, photographs, images, document layouts, artwork, text, fonts, software tools, and similar design and graphical content (referred to herein as “Design Content”). Such Design Content may be accessed and used by Member for the sole purpose of creating, operating and maintaining Member Sites through the Hosting Service. To the extent Designgenics provides Member access to and use of Design Content, Designgenics grants Member a non-exclusive, revocable, non-transferable, non-assignable, limited license to copy, use, reproduce, modify, and publish the Design Content for the sole purpose of creating, operating and maintaining the Member Sites through the Hosting Service during the term of the Member's Hosting Service Account. Member acknowledges and agrees that Designgenics or its licensors own all legal right, title and interest in and to such Design Content, including any intellectual property rights. All rights in such Design Content are reserved worldwide and Designgenics reserves all rights not expressly granted herein, including, without limitation, title, ownership, intellectual property rights, and all other rights and interest in the Design Content. It is strictly prohibited for Member or any other third party to use, modify, retain, copy, distribute, transmit, publish, prepare derivative works of, or use any portion of the Design Content except as expressly allowed in this Agreement for the sole purpose of creating, operating and maintaining the Member Site through the Hosting Service during the term of the Member's Hosting Service Account. Member, and not Designgenics, is entirely responsible for its use of Design Content on the Member Site and for its combination with any other information or Member Content. Designgenics is providing such Design Content to Member only as a convenience, and the inclusion of such content does not imply endorsement by Designgenics of such content. Designgenics reserves the right to add to, delete from, modify or remove completely any part of the Design Content at any time without prior notice, but Designgenics is not responsible for any failure or delay in doing so. Without limiting the generality of the foregoing, upon any termination of Member's Hosting Service Account and/or the Hosting Service, the foregoing license shall automatically terminate and Member must immediately cease all use of and access to the Design Content.
<br><br>
16. Indemnification
Member agrees to indemnify, defend and hold Designgenics and its suppliers, licensors, affiliates, partners, subsidiaries, employees, representatives, agents and members (collectively, the "Indemnified Parties") harmless from and against any and all claims and demands, losses, liability, costs and expenses (including, but not limited to, attorneys' fees and dispute resolutions costs) (collectively, “Liabilities”), incurred by an Indemnified Party arising out of or related to (i) Member's breach of this Agreement including without limitation Member’s breach of any of its representations and warranties or covenants herein; (ii) the creation, use, or maintenance of Member Sites, Member Content, Member Data or End-User Data, including, without limitation, any allegation that any Member Content or any other information or content not provided by Designgenics and contained on Member Sites (including, without limitation, any such Member Content contained in a domain name selected by Member for use with the Member Site) infringes a third person's copyright, trademark or other proprietary or intellectual property right, or misappropriates a third person's trade secrets or is unlawful, threatening, abusive, harassing, tortious, defamatory, obscene, harmful, libellous, invasive of another's privacy, hateful, or racially or ethnically objectionable; (iii) any dispute or litigation between an Indemnified Party and a third party or any other third party claim caused by, arising from or relating to Member's actions or omissions in relation to this Agreement, any Member Content, the Services or the Member Sites, including, without limitation, any domain name disputes involving the domain name selected by Member for use with the Member Site; (iv) Member's negligence or intentional misconduct; or (v) Member’s business dealings with any of its customers, including, without limitation the provision of any products or services to such customers. (vi) The member agrees to safeguard Designgenics from any costs due to non-compliance on its part. These obligations will survive any termination of Member's Service Account or Member's use of the Services and Member Sites or expiry or termination of this Agreement. To the fullest extent permitted by law, the foregoing indemnity will apply regardless of any fault, negligence, or breach of warranty or contract of Designgenics and/or its suppliers, licensors, affiliates, partners, subsidiaries, employees, representatives, agents and/or members.
<br><br>
17. Designgenics Proprietary Trademarks/ Notices
Designgenics,Designgenics.in, Designgenics.com, the Designgenics logo, Designgenics Site Builder and other Designgenics owned or licensed logos and product and service names used in connection with the Services and Member Sites, are trademarks of Designgenics or its licensors (the “Service Marks"). Member agrees not to display or use the Service Marks in any manner whatsoever without Designgenics’s prior written consent. From time to time Designgenics may in itits sole discretion offer a limited license to Member to display Designgenics award logos or other symbols of merit on Member Sites after Designgenics in its sole discretion confers such distinctions to applicable Members. However, Designgenics reserves the right to withdraw such logos or symbols and delete them in its sole discretion for any reason.
<br><br>
18. Modification/Availability of the Hosting Service
Designgenics reserves the right, in its sole discretion, at any time and from time to time, to modify, replace, remove, suspend or discontinue the Website Service, temporarily or permanently, (or any part or feature thereof), including the imposition of limits on certain features and services or restriction of access to parts or all of the Website Service, with or without notice. Designgenics also reserves the right, in its sole discretion, at any time, to cancel, suspend, disable or refuse access to the Website Service, Member Sites or Member Content of any Member or any third party, with or without prior notice. In addition, Member understands and acknowledges that features and components of the Website Service and Member Sites may be suspended, limited, and/or terminated due to actions taken by third party suppliers, licensors, and regulators, such as TPDNVs. Member agrees that Designgenics shall not be liable to Member or to any third party for any modification, suspension or discontinuance of the Website Service, or for any cancellation, suspension, disabling or refusal of access to the Website Service, Member Sites or Member Content of any Member or any third party. If Member does not agree to any such modifications, Member's sole and exclusive remedy is to cancel Member’s Website Account. While Designgenics endeavors to ensure that the Website Service is available at all times, Designgenics shall not be liable if for any reason, the Website Service is unavailable at any time or for any period. Member acknowledges and agrees that if Designgenics disables Member’s access to the Website Service, Member will not be able to access Member’s Website Account details, Member Data, or Member Content.
<br><br>
19. Termination/Cancellation of Member's Hosting Service Account
Either Member or Designgenics may terminate or cancel Member’s Service Account and/or Member's use of and access to all or part of the Services and Member Sites at any time, as follows:
a. Termination by Member. Member may cancel Member’s Service Account or any part of the Services at any time. To cancel, Member must contact customer support through the website URL referenced in Section 4 above. Member will receive a cancellation confirmation via email after Designgenics processes Member's cancellation request. Upon confirmation of such cancellation, Designgenics will refund on pro rata basis . Designgenics also reserves the right to collect fees incurred before Member cancels Member’s Service Account in addition to any applicable cancellation fee(s).
Member must provide Designgenics with the following information in order for Designgenics to process the cancellation:
(a) The exact name of the Services that Member would like to cancel; (b) Member's email address; (c) Member's billing information, including the credit card number that the Member used when purchasing the Services; and (d) Member's reason for cancelling the Services.
b.Termination by Designgenics. Designgenics, in its sole discretion, may terminate Member’s Service Account and this Agreement and Member's use of and access to the Services and Member Sites, including without limitation any related domain names, at any time and for any reason, including, without limitation, (i) if Member breaches this Agreement, including, without limitation, due to (X) failure of Member to make any required payments to Designgenics when due, or (Y) failure of Member to comply with the member conduct rules set forth in this Agreement, including without limitation Sections 8 and 12 above; (ii) if Designgenics is unable to verify or authenticate any information that Member provides to Designgenics; (iii) Designgenics concludes in its sole discretion that Member’s use of or access to the Services or Member Sites may result in liability to Designgenics or its suppliers or licensors, or (iv) upon the bankruptcy or insolvency of Member, or (v) Designgenics concludes in its sole discretion that Member is convicted of a felony or involved in a serious offense related to financial activities, or is judged by a court to have committed fraud or breach of fiduciary duty, or is the subject of a judicial determination that Designgenics reasonably deems as the substantive equivalent of any of these. If Designgenics terminates Member's Service Account pursuant to (i), (ii), (iii), (iv) or (v) above, Member will forfeit all credits, pre-paid fees, and any other amounts accruing to Member, if any, and Designgenics shall not be required to refund, redeem, or pay any such or other amounts to Member.
c. Effect of Termination. Upon cancellation or other termination of Member’s Service Account for any reason, Designgenics shall (a) collect all fees, commitments and obligations incurred or accrued by Member; (b) delete any or all Member Content, Member Data, End-User Data, listings, messages or other information in connection with Member’s Service Account and Member’s use of or access to the Services and Member Site; (c) all unfulfilled obligations and liabilities of Member under such agreements and Designgenics’s rights under this Agreement which shall survive termination of this Agreement, and (d) prohibit Member's access to and use of Member’s Service Account, the Services and the Member Sites, including without limitation by deactivating Member's password. In no event shall Designgenics be required to return any Member Content to Member upon any such termination. Designgenics is not responsible for any damages to or losses incurred by Member or any third party in the event Member chooses to cancel the Member’s Service Account and Designgenics takes any of the above actions.
Notwithstanding anything contained herein, Member understands and agrees that Member’s cancellation of Member’s Service Account is Member's sole and exclusive right and remedy with respect to any dispute with Designgenics. This includes, but is not limited to, any dispute related to, or arising out of: (1) any term of this Agreement or Designgenics’s enforcement or application of any such term; (2) any policy or practice of Designgenics or Designgenics’s enforcement or application of these policies; (3) any content available through the Services or any change in content provided through the Services; (4) Member’s ability to access or use the Services or Member Sites; or (5) the amount or type of fees, surcharges, applicable taxes, billing methods or change to the fees, applicable taxes including GST, surcharges or billing methods, if any
<br><br>
20. Data Privacy and Security
Designgenics utilizes reasonable physical, electronic and procedural safeguards to help Designgenics protect against the loss, misuse, disclosure and alteration of any personal data Designgenics receives from Member or about Member’s end users or customers (“End-User Data”). Member is considered to be the controller of such End-User Data, and is responsible for complying with all consumer protection and data privacy laws with respect to such End-User Data, and will indemnify, defend, and hold harmless Designgenics and each other Indemnified Party from and against any and all Liabilities incurred by Designgenics and or an Indemnified Party arising out of or related to Member’s failure to so comply.
<br><br>
21. Notice
Statements, notices and other communications to Member may be made by mail, email, postings within the Website Service or Designgenics’s website, or other reasonable means. Member shall be solely responsible for updating the account's registered email and postal address. Designgenics shall not be responsible for any undelivered notices caused by Member's failure to update the account information. Without limiting the generality of the foregoing, Designgenics may provide notices of changes to this Agreement and the Website Service by displaying notices or links to notices generally on the Designgenics website. Member should refer to the Website - dashboard on Designgenics’s website for information on how to contact and/or provide notice to Designgenics.
<br><br>
22. General
If any provision of this Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced. Designgenics’s failure to exercise or enforce any right or provision of the Agreement shall not constitute a waiver of such right or provision. Member shall not assign this Agreement or any rights or obligations hereunder, by operation of law or otherwise, without prior written approval of Designgenics, and any such attempted assignment shall be void-ab-initio. Designgenics shall have the right to freely assign all or part of this Agreement, and its rights and obligations hereunder, to any third party without requiring the consent of or notice to Member. Subject to the foregoing, this Agreement shall be binding upon and inure to the benefits of Member, and its successors and permitted assigns and Designgenics and its successors and assigns. This Agreement sets forth the entire understanding and agreement between Designgenics and Member with respect to the subject matter hereof. The section and subsection titles in the Agreement are for convenience only and have no legal or contractual effect. Member and Designgenics are an independent parties and not agents or representative of each other. Member shall not have any right or authority to create any obligation or make any representation or warranty in the name or on behalf of Designgenics. This Agreement shall not be interpreted or construed to create an association, joint venture or partnership between Member and Designgenics or to impose any partnership obligation or liability upon Designgenics. Member and Designgenics hereby expressly acknowledge and agree that this Agreement may be entered into electronically, and without the necessity of written signatures.
<br><br>
23. Independent Review
MEMBER ACKNOWLEDGES THAT MEMBER HAS READ AND FULLY UNDERSTOOD THIS AGREEMENT AND ALL RELATED POLICIES REFERENCED AND INCORPORATED IN THIS AGREEMENT AND THAT MEMBER AGREES TO ALL ITS TERMS AND CONDITIONS. MEMBER HAS INDEPENDENTLY EVALUATED ALL ASPECTS OF THIS AGREEMENT AND THE DESIRABILITY OF ENTERING INTO THE TRANSACTIONS CONTEMPLATED IN THIS AGREEMENT AND IS NOT RELYING ON ANY REPRESENTATION, GUARANTEE OR STATEMENT OTHER THAN THOSE EXPRESSLY SET FORTH IN THIS AGREEMENT. IN ENTERING INTO THIS AGREEMENT AND ACCEPTING THE TERMS AND CONDITIONS SET FORTH HEREIN, MEMBER REPRESENTS THAT IT HAS RELIED UPON THE LEGAL ADVICE OF ITS ATTORNEYS/LEGAL ADVISORS. NOTWITHSTANDING THE IDENTITY OF THE DRAFTERS OF THIS AGREEMENT, THE PARTIES HERETO AGREE THAT THERE WILL BE NO PRESUMPTION FOR OR AGAINST ANY PARTY ARISING OUT OF OR RELATING TO THE IDENTITY OF SUCH DRAFTERS.
<br><br>
24. Internet Domain Names
a. Designgenics owns the primary domain names listed on Schedule 1 attached hereto, as such Schedule may be updated by Designgenics from time to time in its sole discretion (the “Primary Domains”). Customer does not have any ownership interest or rights of any kind to any of the Primary Domains. If Customer subscribes for the ‘Starter Hosting Service’, Designgenics will register, through one or more third party vendors’ subdomain name(s) under the applicable Primary Domain for use with the Member Site----e.g., “[Name of Member Business].vpweb.com” (collectively, “Standard Subdomains”). Designgenics will own and control all Standard Subdomains. Customer will not have any ownership interest in any Standard Subdomain, but will have a limited, revocable, non-exclusive, non-transferable, non-assignable license to use such Standard Subdomain solely during the term of Member's Service Account in connection with the operation of its Member Sites through the Services.
b. Member may request Designgenics to acquire, if available, customized top-level domain name(s) for use in connection with the Member Sites as part of an upgraded Services (collectively, the “Member Domain Name”). Subject to clause c of this Section , Designgenics will use its reasonable commercial efforts to register the Member Domain Name if available, and, if successful in registering the Member Domain Name, will serve as registrant with respect to such Member Domain Name and will own and control the Member Domain Name (“Registrant”). Customer will not have any ownership interest in any such Member Domain Name, but will have a limited, revocable, non-exclusive, non-transferable, non-assignable, license to use such Member Domain Name solely during the term of the Member's Service Account in connection with the operation of its Member Sites through the Services. Without limiting the generality of the foregoing, upon any termination of Member’s Service Account, Member will have no further access to or use of the Member Domain Name.
By requesting that Designgenics register a Member Domain Name for the Member Site through the Service, Member hereby represents and warrants to Designgenics that (a) all information Member provides to Designgenics for purposes of registering the Member Domain Name and serving as Registrant therefore is complete and accurate; (b) the registration of the Member Domain Name will not infringe upon or otherwise violate the rights of any third party; (c) Member is not seeking to have the Member Domain Name registered for an unlawful purpose; and (d) Member will not knowingly use the Member Domain Name in violation of any applicable laws or regulations. It is solely Member’s responsibility to determine whether the Member Domain Name registration infringes or violates someone else's rights.
Designgenics may in its sole discretion use one or more TPDNVs who are ICANN accredited registrars, to provide domain name registration services in connection with the Member Domain Names. In cases where Designgenics serves as the Registrant for the Member Domain Name, Designgenics will have entered into the TPDNV’s terms of service with respect to such registration, which the TPDNVs may modify, amend or alter from time to time (the “TPDNV Registration Agreement”). A copy of the current form of TPDNV Registration Agreement is attached hereto as Annex A and incorporated by reference herein. Member agrees and understands that Member is required to fully comply with all of the obligations imposed upon Designgenics as a party to the TPDNV Registration Agreement with respect to the creation, operation, and maintenance of the Services and Member Site to the same extent as if Member were directly a party thereto, and the TPDNVs, ICANN and the Registry may have certain rights under the TPDNV Registration Agreement and related policies, rules and regulations that can be enforced against or in relation to Member. Member will remain liable to Designgenics, the TPDNV, ICANN, the Registry and other third parties to the extent of any violation of any of the terms and conditions of the TPDNV Registration Agreement or any related policies, rules, procedures, and regulations to the extent caused by or resulting from the actions or omissions of Member or any of its affiliates, agents, employees, representatives, or customers. Accordingly, without limiting any other remedies available to Designgenics under this Agreement or at law or in equity, Member agrees to indemnify, defend and hold the Indemnified Parties harmless from and against any and all Liabilities incurred by them arising out of or related to any such actions or omissions.
c. Under certain circumstances, Designgenics may in its sole discretion elect to offer to certain Members the opportunity to own and control their Member Domain Names and to serve as Registrant in connection with such Member Domain Names. In all such cases, Member must enter into the TPDNV’s then current TPDNV Registration Agreement directly with the TPDNV prior to such registration. Without limiting the generality of the foregoing or any of the terms and conditions set forth in the TPDNV Registration Agreement, as set forth in the TPDNV Registration Agreement, in such cases Member must also agree to the terms and conditions of the ICANN Uniform Domain Name Dispute Resolution Policy as then in effect, a copy of the current version of which is attached hereto as Annex B and incorporated by reference herein, which may be modified, altered or amended by ICANN at any time in its sole discretion. Member understands that Member is creating a separate contractual relationship between Member and each of the TPDNV and ICANN with respect to the Member Domain Name by agreeing to the TPDNV Registration Agreement and ICANN Uniform Domain Name Dispute Resolution Policy, as applicable, and that Member, and not Designgenics, is responsible for all liability and obligations in connection with those contracts. If, after registering one or more Member Domain Names as Registrant, Member chooses to delete a previously registered Member Domain Name and subsequently register one or more additional different Member Domain Names, Member will be charged the resulting domain name registration fees.
In cases where Member serves as Registrant of the Member Domain Names, Member will be listed as the Registrant and administrative contact in connection with Member's Member Domain Name; however, Designgenics may in its sole discretion temporarily list itself as the Registrant and administrative contact in the event that it changes to a different TPDNV until the TPDNV change is completed. In such cases, Member hereby authorizes Designgenics to list itself as the billing contact, technical contact and name servers in connection with Member's Member Domain Name and to take any actions Designgenics deems appropriate in those capacities. However, upon termination of the Member's Service Account, Designgenics will immediately cease acting in those capacities. After such time, Designgenics will not be responsible to forward any notices, emails or other correspondence to Member or to take any other actions in connection with Member's Member Domain Name. Additionally, in the event that Member’s Service Account is suspended or terminated by Designgenics for lack of payment or any other reason or is cancelled by Member, Designgenics shall not renew any domain names that may become due for renewal during the suspension of the account or following termination. Member will be solely responsible for all ongoing fees, as well as removing Designgenics as the billing, technical contact and name servers in connection with such Registrant-owned Member Domain Names.
d. Without limiting any other remedies available to Designgenics under this Agreement or at law or in equity, Designgenics, in its sole discretion, reserves the right at any time to deny, cancel, suspend, transfer or modify any domain name registration (i) to correct a mistake, (ii) if Designgenics is notified or discovers that a complaint has been filed with a judicial or administrative body or other third party, including without limitation ICANN, the Registry or the TPDNV, challenging the registration, reservation or use of Member’s domain name, (iii) to protect the integrity and stability of Designgenics, (iv) to comply with any applicable laws, government rules, or requirements, requests of law enforcement, or dispute resolution process, (v) to avoid any liability, civil or criminal, or (vi) if the TPDNV, ICANN or the Registry denies, cancels, suspends or transfers the domain name in accordance with such entities’ agreements or policies then in effect. Member agrees and understands that Designgenics shall have no liability to Member or any other person or entity for any damages, costs, expenses or other losses that may arise from any refusal to register, cancellation, suspension, transfer or modification of Member’s domain name registration in accordance with the foregoing sentence or otherwise.
e. Member agrees and acknowledges that Designgenics will make domain name registration information Member provides available to ICANN, to TPDNVs, to the Registry administrators, law enforcement agencies and to other third parties as necessary to fulfillfulfil its obligations under this Agreement or any other agreement with any person or to comply with applicable laws, rules, regulations and policies thereof. Member further agrees and acknowledges that Designgenics may make publicly available, or directly available to third party vendors, some or all, of the domain name registration information Member provides, for purposes of inspection (such as through a Whois service) or other purposes as required or permitted by ICANN and applicable laws. Member hereby consents to any and all such disclosures and use of, and guidelines, limits and restrictions on disclosure or use of, information provided by Member in connection with the registration of a domain name (including any updates to such information), whether during or after the term of the registration of the domain name. Member hereby irrevocably waives any and all claims and causes of action Member may have arising from such disclosure or use of Member’s domain name registration information by Designgenics or any third party.
<br><br>
25. Email
To the extent Designgenics in its sole discretion makes available to Members through the Hosting Service email services provided by one or more independent Third Party Email Services Vendor (each, a "TPESV"), Designgenics will not be responsible for the actions or inaction of the then current TPESV or the unavailability or malfunction of its network or services. Designgenics may change a TPESV, if any, at any time and from time to time in its sole discretion. Designgenics is not a party to, and shall not be involved in or responsible for, any transactions, agreements, and/or disputes between Member and the TPESV ("TPESV Dispute"). In the event of a TPESV Dispute, Member hereby releases Designgenics (and its officers, directors, agents, affiliates, and employees) from claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes. By using email services, if any, Member further agrees to the terms and conditions contained in Designgenics’s then current Email Services Policy, a copy of which will be attached to this Agreement and incorporated by reference herein.
<br><br>
26. Governing Law and Dispute Resolution
26.1 This Agreement shall be governed by and construed in accordance with the laws of India. 26.2 In the event any dispute or difference arises out of or in connection with the interpretation or implementation of this Agreement, or out of or in connection with the breach, or alleged breach of this Agreement (hereinafter referred to as the “Dispute”) between Designgenics and Member, both of them shall attempt in the first instance to resolve the Dispute through friendly consultations. If the Dispute is not resolved through friendly consultations within fifteen (15) days after either of the party informing the other party in writing of the existence of the Dispute, then either party may refer the dispute for resolution by arbitration. Such arbitration shall be governed by the provisions of the Arbitration and Conciliation Act of 1996 or any statutory re-enactment or modification for the time being in force. Either Party shall be entitled to apply to the competent courts for interim or interlocutory relief in respect of such arbitration. The arbitration shall be held at Mumbai in the following manner: 26.2.1 All proceedings in any such arbitration shall be conducted in English. 26.2.2 There shall be a sole arbitrator appointed by Designgenics. 26.2.3 The arbitration award made by the sole arbitrator shall be final and binding on the Parties and the Parties agree to be bound thereby and to act accordingly. The award shall be enforceable in any competent court of law. 26.2.4 The award shall be reasoned and shall be in writing. 26.2.5 The sole arbitrator may (but shall not be required to) award to the party that substantially prevails on merits, its costs and reasonable expenses (including reasonable fees of its counsel). 26.3 Subject to Clause 26.2, the courts at Mumbai shall have exclusive jurisdiction over any of the disputes arising out of or in connection with this Agreement

</td>
		</tr>

</table>


<div class="footer">
	<br>
	<table width="60%" align="center" border="0">
		<tr>
			<td align="center"><p class="p4"><a href="aboutus.php">about us</a></p></td>
			<td align="center"><p class="p4"><a href="terms.php">terms of use</a></p></td>
		</tr>

		<tr>
			<td align="center"><p class="p4"><a href="contact.php">Contact & Connect us</a></p></td>
			<td align="center"><p class="p4"><a href="copyright.php">Copyright matters</a></p></td>
		</tr>

		<tr>
			<td align="center"><p class="p4"><a href="https://www.google.com/maps/place/SIES+College+of+Management+Studies+(SIESCOMS)/@19.0423729,73.0207947,17z/data=!3m1!4b1!4m5!3m4!1s0x3be7c3db667e6227:0x211c75f6b08e5123!8m2!3d19.0423729!4d73.0229834">locate us</a></p></td>
			<td align="center"><p class="p4"><a href="patent.php">Patents and Trademark</a></p></td>
		</tr>
		<tr>
			<td align="center" colspan="2" height="50">@<b>Designgenics</b> 2019-2020 All rights reserved.</td>
		</tr>
 </table>
</div>

</body>
</html>



